"use client";

import { useEffect, useMemo, useState } from "react";
import { FileText, Hash, LoaderCircle, Search, UserRound, X } from "lucide-react";
import type { SearchResults } from "@/lib/rundesk/types";

const emptyResults: SearchResults = { messages: [], channels: [], tasks: [], users: [] };
type Filter = "all" | "messages" | "tasks" | "people" | "channels";
export default function SearchPanel({ workspaceId, channelId, channelName, onClose, onOpenChannel, onOpenMessage }: { workspaceId: string; channelId?: string; channelName?: string; onClose: () => void; onOpenChannel?: (channelId: string) => void; onOpenMessage?: (channelId: string, messageId: string) => void }) {
  const [query,setQuery]=useState(""),[results,setResults]=useState<SearchResults>(emptyResults),[loading,setLoading]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState<Filter>(channelId?"messages":"all"),[attachmentsOnly,setAttachmentsOnly]=useState(false);
  useEffect(()=>{if(!query.trim())return;const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);setError("");const qs=new URLSearchParams({workspaceId,q:query});if(channelId)qs.set("channelId",channelId);if(attachmentsOnly)qs.set("hasAttachment","true");fetch(`/api/search?${qs}`,{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Search failed");return payload as SearchResults}).then(setResults).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:"Search failed")}).finally(()=>setLoading(false))},220);return()=>{window.clearTimeout(timer);controller.abort()}},[query,workspaceId,channelId,attachmentsOnly]);
  const counts=useMemo(()=>({messages:results.messages.length,tasks:results.tasks.length,people:results.users.length,channels:results.channels.length}),[results]);
  const visible=(kind:Exclude<Filter,"all">)=>filter==="all"||filter===kind;
  return <aside className="detail-panel search-panel"><header><div><h2>{channelId?"Find in Channel":"Search Rundesk"}</h2>{channelId&&<span>#{channelName}</span>}</div><button onClick={onClose}><X size={18}/></button></header><label className="panel-search"><Search size={16}/><input autoFocus value={query} onChange={event=>{const next=event.target.value;setQuery(next);if(!next.trim()){setResults(emptyResults);setError("")}}} placeholder={channelId?"Search messages":"Search messages, channels, tasks, people"}/></label><div className="search-filter-row">{!channelId&&<>{(["all","messages","channels","tasks","people"] as Filter[]).map(item=><button className={filter===item?"active":""} key={item} onClick={()=>setFilter(item)}>{item[0].toUpperCase()+item.slice(1)}{item!=="all"&&query&&<small>{counts[item as keyof typeof counts]}</small>}</button>)}</>}<label><input type="checkbox" checked={attachmentsOnly} onChange={event=>setAttachmentsOnly(event.target.checked)}/>Has attachment</label></div><div className="search-results">{loading&&<div className="panel-center"><LoaderCircle className="spin"/></div>}{!query&&<div className="panel-empty"><span className="empty-icon"><Search size={28}/></span><strong>{channelId?"Try searching for something":"Search your workspace"}</strong><p>{channelId?"Find messages in this conversation.":"Find channels, messages, tasks, and people."}</p></div>}{error&&<p className="form-error">{error}</p>}
    {visible("channels")&&results.channels.length>0&&!channelId&&<section><h3>Channels</h3>{results.channels.map(item=><button key={item.id} onClick={()=>{onOpenChannel?.(item.id);onClose()}}><Hash size={14}/><span><strong>{item.name}</strong><small>{item.description||"Channel"}</small></span></button>)}</section>}
    {visible("people")&&results.users.length>0&&!channelId&&<section><h3>People</h3>{results.users.map(item=><button key={item.id}><UserRound size={14}/><span><strong>{item.name}</strong><small>{item.email}</small></span></button>)}</section>}
    {visible("messages")&&results.messages.length>0&&<section><h3>Messages</h3>{results.messages.map(item=><button key={item.id} onClick={()=>{onOpenMessage?.(item.channelId,item.id);onClose()}}><span><strong>#{item.channel.name} · {item.author.name}</strong><small>{item.content}</small></span></button>)}</section>}
    {visible("tasks")&&results.tasks.length>0&&!channelId&&<section><h3>Tasks</h3>{results.tasks.map(item=><button key={item.id}><FileText size={14}/><span><strong>{item.title}</strong><small>{item.status.replace("_"," ")} · {item.priority}</small></span></button>)}</section>}
    {query&&!loading&&!error&&!results.channels.length&&!results.users.length&&!results.messages.length&&!results.tasks.length&&<div className="panel-empty"><span className="empty-icon"><Search size={28}/></span><strong>No matching results</strong><p>Try another search term or remove a filter.</p></div>}</div></aside>;
}
